version: '3.4'

services:
  fastproject:
    image: ${DOCKER_REGISTRY-}fastproject
    build:
      context: .
      dockerfile: FastProject/Dockerfile
    networks:
      - fast_project

  project.database:
    image: postgres:latest
    container_name: project.database
    environment:
      - POSTGRES_DB=projects
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - projects-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fast_project

networks:
  fast_project:

volumes:
  projects-db: